### ISSUE TITLE
remove SS switching on __dpmi_int()

### ISSUE THREAD

**Issue by stsp** [jwt27/djgpp-cvs#13]
Please see this commit:
https://github.com/stsp/dj64dev/commit/f1434184b278e481523a2f6c150ebd1f0f938e50
Do you know why SS was touched there?
I think it is a plain bug (may be wrong of course),
and I'd like djgpp to have that fixed too,
in which case I will be able to remove the
"emergency stack" from all clients.

**Comment by jwt27** [comment]
I think I know what it's intended for:

DPMI ax=0300 is the only function that can read the caller's stack (if CX non-zero).  But the application's SS/DS/ES may be invalidated at any time from IRQ 0 (by setting segment limit to zero, in order to call `SIGPROF` handler from an exception frame).  That would trigger a page fault in ring 0, instant crash.

But, I don't fully see how this applies here.  Since CX is always zero, there should be no reason for DPMI to access the stack.

And clearly, `__dpmi_int()` is not meant to be called from LPMS or any foreign stack.  Which I think is a reasonable assumption to make for libc functions.

**Comment by stsp** [comment]
> invalidated at any time from IRQ 0

The counter-measure in question is
then inadequate, because you'd need
to disable IRQs first, to make sure its
not re-set to 0 after your mov %ss.

Also I am not sure where have you
actually found such SIGPROF technique.
In djgpp sources I only see `raise(SIGPROF)`
in a timer handler.

> And clearly, __dpmi_int() is not meant to be called from LPMS or any foreign stack. Which I think is a reasonable
> assumption to make for libc functions.

Posix explicitly documents `sigaltstack()`
and lists the set of async-safe functions:
https://man7.org/linux/man-pages/man7/signal-safety.7.html
This is quite a large set as you can see,
that most importantly includes `read()`
and `write()`. They are useful in an async
contexts by their ability to write to terminal,
not necessarily to a file.

Besides the function list, posix additionally
says:
```
       (An implementation may provide safe
       implementations of additional functions, but this is not required
       by the standard and other implementations may not provide the
       same guarantees.)
```
So its clear that the lib should at least try
to provide an extra functions in an async-safe
way. For example when I register the real-mode
callback for mouse handler, I use a few conio
functions from there, like `wherex()`, `wherey()`.

Anyway, as it is now, practically no functions
are sync-safe or sigaltstack-friendly. The above
posix requirement is clearly violated.
And for what? There is no advantage from that
line that clobbers SS.

**Comment by stsp** [comment]
Also note that `__dpmi_simulate_real_mode_interrupt()`
doesn't do this. Only `__dpmi_int()` does.

**Comment by stsp** [comment]
Of course I do realize that posix never
says `sigaltstack()` is allowed to alter SS,
so all the references to posix are vague.
Its just that generally posix asks you to
stay async-safe when possible.
What's more important is that if `__dpmi_int()`
does the same as `__dpmi_simulate_real_mode_interrupt()`,
then your mouse call-back won't need the
emergency stack for a mere calls to `wherey()`.

**Comment by jwt27** [comment]
> > invalidated at any time from IRQ 0
> 
> The counter-measure in question is then inadequate, because you'd need to disable IRQs first, to make sure its not re-set to 0 after your mov %ss.

There are only two selectors here: `__djgpp_app_DS` can be invalidated, `__djgpp_ds_alias` is always valid.  The latter is used in exception/interrupt contexts (otherwise you get recursive GP faults).

> Also I am not sure where have you actually found such SIGPROF technique. In djgpp sources I only see `raise(SIGPROF)` in a timer handler.

And this timer signal is raised from the exception handler (from `exceptn.S`, jumps to `__djgpp_exception_processor()`).  It's a bit convoluted.
For profiling this is necessary, since DPMI doesn't give any information about the client state in a hardware interrupt.  So by intentionally triggering an exception soon after the IRQ, you get an EIP to sample, which roughly corresponds to the location where the timer interrupt triggered.

> > And clearly, __dpmi_int() is not meant to be called from LPMS or any foreign stack. Which I think is a reasonable
> > assumption to make for libc functions.
> 
> Posix explicitly documents `sigaltstack()` and lists the set of async-safe functions: https://man7.org/linux/man-pages/man7/signal-safety.7.html This is quite a large set as you can see, that most importantly includes `read()` and `write()`. They are useful in an async contexts by their ability to write to terminal, not necessarily to a file.
> 
> Besides the function list, posix additionally says:
> 
> ```
>        (An implementation may provide safe
>        implementations of additional functions, but this is not required
>        by the standard and other implementations may not provide the
>        same guarantees.)
> ```
> 
> So its clear that the lib should at least try to provide an extra functions in an async-safe way. For example when I register the real-mode callback for mouse handler, I use a few conio functions from there, like `wherex()`, `wherey()`.
> 
> Anyway, as it is now, practically no functions are sync-safe or sigaltstack-friendly. The above posix requirement is clearly violated. And for what? There is no advantage from that line that clobbers SS.


You can have as many stacks as you want, within the same flat memory area.  Eg. for userland threads.

The compiler also also assumes the flat memory model, so it is allowed to do:

```asm
lea ebp, [some_ptr]
mov [ebp], 123      # data via SS
```
or
```asm
mov eax, esp
mov [eax], 123      # stack via DS
```

Therefore in C code, CS/DS/ES/SS must always point to the same area (but the selectors may be different).

**Comment by stsp** [comment]
> There are only two selectors here: __djgpp_app_DS can be invalidated, __djgpp_ds_alias is always valid.
> The latter is used in exception/interrupt contexts (otherwise you get recursive GP faults).

Ok, thanks for info.
I now understand what happens:
it clobbers the limit of `__djgpp_app_DS`
to get the stack fault, but running on
`___djgpp_ds_alias` means no fault.
I am shocked someone did that, because
you have the profiler hooks here:
https://gcc.gnu.org/onlinedocs/gcc-4.4.2/gcc/Code-Gen-Options.html
```
-finstrument-functions
    Generate instrumentation calls for entry and exit to functions. Just after function entry and just before function exit, the following profiling functions will be called with the address of the current function and its call site. (On some platforms, __builtin_return_address does not work beyond the current function, so the call site information may not be available to the profiling functions otherwise.)

              void __cyg_profile_func_enter (void *this_fn,
                                             void *call_site);
              void __cyg_profile_func_exit  (void *this_fn,
                                             void *call_site);
```
So why not to use those instead?

> The compiler also also assumes the flat memory model, so it is allowed to do:

Not sure what you mean by "flat" here:
they neither have zero base, nor a 4G limit.

Its rather obvious that since djgpp allows
to register the real-mode callbacks directly
to a C function, rather than the asm wrapper
that could at least switch the stack (dj64
OTOH insists on an asm wrapper, but for
a different reason), then it MUST support
lpms.
In dj64 that was done by the aforementioned
commit, and no further work is needed.

You are right that with djgpp the things
are slightly more complicated. But all you
need is to use the gcc-provided profiler
hooks instead of an SS hackery. Then the
problem doesn't exist also for djgpp.

**Comment by jwt27** [comment]
> > There are only two selectors here: __djgpp_app_DS can be invalidated, __djgpp_ds_alias is always valid.
> > The latter is used in exception/interrupt contexts (otherwise you get recursive GP faults).
> 
> Ok, thanks for info. I now understand what happens: it clobbers the limit of `__djgpp_app_DS` to get the stack fault, but running on `___djgpp_ds_alias` means no fault. I am shocked someone did that, because you have the profiler hooks here: https://gcc.gnu.org/onlinedocs/gcc-4.4.2/gcc/Code-Gen-Options.html
> 
> So why not to use those instead?

Both are used.  With `-pg` the compiler essentially puts `call mcount` at each function entry, this builds the call graph.  But it must also sample EIP at regular intervals to find where most time is spent.

The same forced-exception trick is also used for SIGINT/SIGQUIT, since you are allowed to `longjmp()` out from an exception, but not from the keyboard interrupt.  Side effect: Ctrl-C does nothing if your program is stuck in a tight loop with no memory access.

> > The compiler also also assumes the flat memory model, so it is allowed to do:
> 
> Not sure what you mean by "flat" here: they neither have zero base, nor a 4G limit.
> 
> Its rather obvious that since djgpp allows to register the real-mode callbacks directly to a C function, rather than the asm wrapper that could at least switch the stack (dj64 OTOH insists on an asm wrapper, but for a different reason), then it MUST support lpms. In dj64 that was done by the aforementioned commit, and no further work is needed.
> 
> You are right that with djgpp the things are slightly more complicated. But all you need is to use the gcc-provided profiler hooks instead of an SS hackery. Then the problem doesn't exist also for djgpp.

"Flat" meaning all segment registers point to the same area.  So a pointer can be used in any register (EAX, ESP, EIP, etc) and lead to the same memory location.  The compiler has no concept of segment registers, base, limits, etc.  As far as gcc is concerned, memory starts at `(void *)1` and ends at `(void *)UINTPTR_MAX`, there is nothing outside it.

With RMCBs, I think the "raw" function is provided only for users to write their own handler directly in asm, same with IRQs/exceptions (although I don't see it explicitly written out anywhere).  Any C/C++ code must adhere to SS == DS == ES == CS, since gcc doesn't know anything else.


What I suspect happened with `__dpmi_int()`:  it was probably intended to support the stack-copy feature, maybe via some va_list trick.  But this ended up difficult to use, so it was dropped, but the SS switch left in place.  So removing it is fine, but leaving it in place doesn't cause bugs, since SS is assumed to be `__djgpp_app_DS` on entry.

**Comment by stsp** [comment]
> Both are used. With -pg the compiler essentially puts call mcount at each function entry, this builds the call graph.
> But it must also sample EIP at regular intervals to find where most time is spent.

Obviously if you use profiler hooks,
which takes the function address as
an argument, this is not a problem,
as you can just save the pointer to
some global list on entry hook, and
remove it on exit hook.
Then your timer handler just needs
to inspect that global list and its last
element will show where we are now.

> "Flat" meaning all segment registers point to the same area.

Please don't override the common definitions.
https://wiki.osdev.org/Segmentation
```
Most C compilers assume a flat-memory model. In this model all the segments cover the full address space
(usually 0->4Gb on x86).
```
Nothing is flat on djgpp.

> So removing it is fine,

I agree with your earlier statements that
it would better be removed as soon as the
profiler doesn't use that technique, even
if the removal doesn't break anything.
As long as this SS switch means "disable
profiling", it is eligible to stay.
So lets discuss why the profiler uses that,
and not the hooks in a way I described
above.

> but leaving it in place doesn't cause bugs, since SS is assumed to be __djgpp_app_DS on entry.

It causes the inability to work with lpms,
aka directly registering the callbacks to C.
And stack switching is a convoluted task
which I don't want to do out of nothing
to do.

**Comment by jwt27** [comment]
> > Both are used. With -pg the compiler essentially puts call mcount at each function entry, this builds the call graph.
> > But it must also sample EIP at regular intervals to find where most time is spent.
> 
> Obviously if you use profiler hooks, which takes the function address as an argument, this is not a problem, as you can just save the pointer to some global list on entry hook, and remove it on exit hook. Then your timer handler just needs to inspect that global list and its last element will show where we are now.

The current method also works for (library) code that is not compiled with `-pg` or other special flags.

> > "Flat" meaning all segment registers point to the same area.
> 
> Please don't override the common definitions. https://wiki.osdev.org/Segmentation
> 
> ```
> Most C compilers assume a flat-memory model. In this model all the segments cover the full address space
> (usually 0->4Gb on x86).
> ```
> 
> Nothing is flat on djgpp.

Depends on perspective.  From gcc's point of view, it is 100% flat.  For asm code that needs to talk to DPMI, it's very segmented.

> > So removing it is fine,
> 
> I agree with your earlier statements that it would better be removed as soon as the profiler doesn't use that technique, even if the removal doesn't break anything. As long as this SS switch means "disable profiling", it is eligible to stay. So lets discuss why the profiler uses that, and not the hooks in a way I described above.
> 
> > but leaving it in place doesn't cause bugs, since SS is assumed to be __djgpp_app_DS on entry.
> 
> It causes the inability to work with lpms, aka directly registering the callbacks to C. And stack switching is a convoluted task which I don't want to do out of nothing to do.

Stack switch is not that difficult.  Make a `char mystack[4096]`, then some wrapper with `mov ss, dword ptr [__djgpp_app_DS]; mov esp, mystack + 4092`.  A single stack is fine since RMCBs are not re-entrant without swapping the register block.

**Comment by stsp** [comment]
> The current method also works for (library) code that is not compiled with -pg or other special flags.

Does it make sense to profile what
wasn't compiled for profiling? I am
sure this can at least be optional, aka
`int _crt0_startup_flags = _CRT0_PROFILE_ME_HARDER;`.
But yeah, I already remember the attempt
to make a descriptor leak w/a similarly
optional...

> Any C/C++ code must adhere to SS == DS == ES == CS, since gcc doesn't know anything else.

This is actually quite wrong, I suspect.
gcc never references data via CS or heap
via SS. gcc doesn't support segmentation
only in a sense that it never generates the
code that switches segments (probably it
does something with %es when fortifying
stack, but doesn't matter). It can live very
well if the startup code sets the separate
segments for code, data and stack.

> From gcc's point of view, it is 100% flat.

gcc doesn't care. It very rarely uses segment
override prefixes at all, maybe only for %es
sometimes. Why do you think it has something
to do with the flatness?
It doesn't care if your code can be accessed
via SS or cannot: it never does that.

> [__djgpp_app_DS]; mov esp, mystack + 4092.

You are forgetting that the stack needs to
be switched back later. So this:
https://github.com/stsp/dj64dev/blob/master/demos/rmcb/asm.inc

**Comment by stsp** [comment]
For example even if you have the
pointer to a function, the call instruction
will just put the value of that pointer
into EIP. gcc doesn't care if there is
some other data at %ds:func_ptr as
it never fetches from that location.
i.e.
```
int (*func_ptr)(void) = some_fn;
int a = *func_ptr; // nonsense, not fetching via function pointer
int a = func_ptr(); // ok, just use call on that ptr
```
So I am not even sure where the "flatness"
can come in. I worked with segments and
gcc on many occasions w/o a slightest problems.
It doesn't support "large" models, i.e. where
it needs to switch the segments itself. But
otherwise it works perfectly ok with segments
(by not caring about them).

**Comment by jwt27** [comment]
> > The current method also works for (library) code that is not compiled with -pg or other special flags.
> 
> Does it make sense to profile what wasn't compiled for profiling? I am sure this can at least be optional, aka `int _crt0_startup_flags = _CRT0_PROFILE_ME_HARDER;`. But yeah, I already remember the attempt to make a descriptor leak w/a similarly optional...

Yes, generally you want to profile the whole program, not just some parts of it.  It it already annoying that you can't profile into real-mode code - you will see your program spend a lot of time in `__dpmi_int()`, but no indication of what it's doing there.

Plus `SIGQUIT`/`SIGINT` and some others also still use the same fake-exception trick, so making this method optional only for `SIGPROF` doesn't seem to solve much.

> > Any C/C++ code must adhere to SS == DS == ES == CS, since gcc doesn't know anything else.
> 
> This is actually quite wrong, I suspect. gcc never references data via CS or heap via SS. gcc doesn't support segmentation only in a sense that it never generates the code that switches segments (probably it does something with %es when fortifying stack, but doesn't matter). It can live very well if the startup code sets the separate segments for code, data and stack.
>
> > From gcc's point of view, it is 100% flat.
> 
> gcc doesn't care. It very rarely uses segment override prefixes at all, maybe only for %es sometimes. Why do you think it has something to do with the flatness? It doesn't care if your code can be accessed via SS or cannot: it never does that.

> For example even if you have the pointer to a function, the call instruction will just put the value of that pointer into EIP. gcc doesn't care if there is some other data at %ds:func_ptr as it never fetches from that location. i.e.
> 
> ```
> int (*func_ptr)(void) = some_fn;
> int a = *func_ptr; // nonsense, not fetching via function pointer
> int a = func_ptr(); // ok, just use call on that ptr
> ```
> 
> So I am not even sure where the "flatness" can come in. I worked with segments and gcc on many occasions w/o a slightest problems. It doesn't support "large" models, i.e. where it needs to switch the segments itself. But otherwise it works perfectly ok with segments (by not caring about them).

You can do:
```c
*(unsigned char *)malloc = 0xcc;
```
I'm sure that is UB in some way, but gcc compiles it with no warnings.  Ok, scratch the CS/EIP case, maybe that could be a different segment.  Still gcc will happily address heap memory via EBP (implicit SS prefix), or stack memory via general-purpose regs (implicit DS prefix).  ES is used for string-ops `movsb`, `cmpsb`, etc, so it must also be the same as DS/SS.

**Comment by stsp** [comment]
> Plus SIGQUIT/SIGINT and some others also still use the same fake-exception trick, so making this
> method optional only for SIGPROF doesn't seem to solve much.

This all can be done with a profiler
hooks. In profiler hook you inspect
some global var (set by int23 handler),
and directly call to the signal handler
if need be.
What can be simpler than that?
This also solves the "profile me harder"
problem by just making the profiler
hooks a mandatory (so that there are
no libs w/o those).

> I'm sure that is UB in some way, but gcc compiles it with no warnings.

This may even work because such a
pointer points to PLT. Otherwise you'd
get a page fault. Anyway, gcc is not
supposed to issue any UB warnings.
ubsan does that (at run-time).

> Still gcc will happily address heap memory via EBP

You mean, in an -fomit-frame-pointer
case?

> or stack memory via general-purpose regs (implicit DS prefix).

I hope not, unless you have some pointer
to a stack object. Without such pointers, I've
got an absolutely stable program with djgpp
(w/o disabling frame pointers of course),
but I agree this can't be fully excluded.
OK in this case I agree that my solution is
dj64-specific, and can't be safely applied to
djgpp. So the ifdefs I already have, should
probably stay...

Thank you.
