### ISSUE TITLE
There is no djgpp.env file after unzipping the archives on MS-DOS 5.0

### ISSUE THREAD

**Issue by cheny0y0** [jwt27/djgpp-cvs#4]
I did this:
UNZIP32.EXE GCC1030B.ZIP
UNZIP32.EXE CSDPMI7B.ZIP

**Comment by jwt27** [comment]
Hi, this is not an "official" djgpp page.  For general questions you should use the mailing list: djgpp@delorie.com

I know the answer though; you are missing package [djdev205.zip](http://www.delorie.com/pub/djgpp/current/v2/djdev205.zip).
You'll also need the assembler and linker from binutils: [bnu237b.zip](http://www.delorie.com/pub/djgpp/current/v2gnu/bnu237b.zip)

**Comment by cheny0y0** [comment]
I know. But I want to know the text in djgpp.env.

**Comment by jwt27** [comment]
The file is also present in this repository: https://github.com/jwt27/djgpp-cvs/blob/master/djgpp.env
